### ISSUE TITLE
useExtendedLib方式引入weui，weui-flex布局无效

### ISSUE THREAD

**Issue by bulangnisi** [wechat-miniprogram/weui-miniprogram#101]
根据文档描述

如何使用
首先要在 app.wxss 里面引入 weui.wxss，如果是通过 npm 引入，需要先构建 npm（“工具”菜单 --> “构建 npm”）

通过 useExtendedLib 扩展库 的方式引入，可省略 import 步骤

@import '/miniprogram_npm/weui-miniprogram/weui-wxss/dist/style/weui.wxss';

**Comment by bulangnisi** [comment]
如何使用
首先要在 app.wxss 里面引入 weui.wxss，如果是通过 npm 引入，需要先构建 npm（“工具”菜单 --> “构建 npm”）

通过 useExtendedLib 扩展库 的方式引入，可省略 import 步骤

@import '/miniprogram_npm/weui-miniprogram/weui-wxss/dist/style/weui.wxss';

**Comment by seasonhuang** [comment]
已修复，无需引 weui.wxss。
