### ISSUE TITLE
Component is not found

### ISSUE THREAD

**Issue by MakerGYT** [wechat-miniprogram/weui-miniprogram#102]
`npm run dev`后生成`miniprogram_dev`目录，所有component组件下均没有js文件，预览失败

**Comment by xysDavid** [comment]
`npm run dev`的过程中有报错吗？

**Comment by JKD128KKK** [comment]
我也是

**Comment by JKD128KKK** [comment]
![image](https://user-images.githubusercontent.com/39514394/83317138-2f73d500-a25d-11ea-8ad9-c799e01f30cd.png)
![image](https://user-images.githubusercontent.com/39514394/83317157-5df1b000-a25d-11ea-909c-b8541d0aef99.png)
每个都报错的

**Comment by cb360** [comment]
me too

**Comment by flyingnn** [comment]
https://juejin.im/post/5e4f8a98e51d4527143e45e6

参考这个文章，最快的办法：
执行 git config --global core.autocrlf false

重新拉代码就没有这个问题了。 @cb360  @JKD128KKK   @MakerGYT
