### ISSUE TITLE
找不到文件 '../components/weui-wxss/dist/style/weui.wxss';

### ISSUE THREAD

**Issue by ruihelin** [wechat-miniprogram/weui-miniprogram#103]
开发工具导入项目，提示 @import '../components/weui-wxss/dist/style/weui.wxss';找不到文件，预览不了…

**Comment by HungryZ** [comment]
刚刚折腾完终于跑起来了，不得不吐槽这个ReadMe写的真是惜字如金。一个没有H5开发经验的人看了一脸懵逼。我的步骤给你说一下，就当是吐槽了
不是直接导入/tools/demo这个文件夹就可以跑的！！
首先要先安装npm
然后在根目录下跑 npm run dev 这个命令（npm run init一直报错有木有！！！，这个命令不需要执行）
命令执行完后会在根目录下生成一个miniprogram_dev文件夹，把这个文件夹导入项目就可以跑起来了🤣🤣

**Comment by HungryZ** [comment]
不好意思那天我看见运行成功就以为搞定了，结果是不运行npm run init是看不到二级页面的
我之所以npm run init会报错是因为node版本太高，降到11就可以运行成功了

**Comment by xysDavid** [comment]
@ruihelin 想问下这边是怎么导入的呢？

**Comment by ruihelin** [comment]
> @ruihelin 想问下这边是怎么导入的呢？

导入项目吗，选择到目录下tools/demo

**Comment by xysDavid** [comment]
> > @ruihelin 想问下这边是怎么导入的呢？
> 
> 导入项目吗，选择到目录下tools/demo

直接导入是不行的，可以参考一下README和2楼的流程，导入的项目目录应该是`miniprogram_dev`才对
