### ISSUE TITLE
VM678:1 Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/weui-miniprogram/cell/cell.wxss:1:1650)

### ISSUE THREAD

**Issue by xieren58** [wechat-miniprogram/weui-miniprogram#109]
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/weui-miniprogram/cell/cell.wxss:1:1650)

button.weui-vcode-btn{min-height:0;background-color:transparent;border:0;outline:0}

**Comment by Tidyzq** [comment]
使用的是什么版本的 weui ?

**Comment by xieren58** [comment]
weui-miniprogram@1.0.3

**Comment by Tidyzq** [comment]
同样的版本无法复现，麻烦给下复现代码片段和复现路径

**Comment by xieren58** [comment]
```html

    <mp-cells>
      <mp-cell ext-class="weui-cell_select weui-cell_select-after">
        <view slot="title" class="weui-label">习题编号</view>
        <picker bindchange="execNumbChange" value="{{ExecNumb - 1}}" range="{{execNums}}">
          <view class="weui-select">{{execNums[ExecNumb - 1]}}</view>
        </picker>
      </mp-cell>
    </mp-cells>
```

VM21361:1 Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/weui-miniprogram/cell/cell.wxss:1:1650)



![image](https://user-images.githubusercontent.com/955484/83127331-9d5cb700-a10c-11ea-9745-2030c395623e.png)

**Comment by Tidyzq** [comment]
提供代码片段通过 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by goodwong** [comment]
我用useExtendedLib方式也显示同样警告⚠️

![image](https://user-images.githubusercontent.com/2283172/83856044-8ee54f80-a74b-11ea-8a80-f81003413b2a.png)

![image](https://user-images.githubusercontent.com/2283172/83856128-af150e80-a74b-11ea-8b96-0fbdd79e38c4.png)

![image](https://user-images.githubusercontent.com/2283172/83856172-bfc58480-a74b-11ea-98ee-e523a914105a.png)

**Comment by beary** [comment]
使用 useExtendedLib 方式引入，警告

```html
<view>
    <mp-cells title="产品列表">
        <mp-cell>
            <view>aaa</view>
            <view slot="footer">bbb</view>
        </mp-cell>
    </mp-cells>
</view>
```

> Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/weui-miniprogram/cell/cell.wxss:1:1744)

**Comment by changjingli** [comment]
代码片段地址：https://developers.weixin.qq.com/s/PNqN9am57cij

**Comment by Tidyzq** [comment]
### 原因
useExtendedLib 引入的 weui 版本过老，新版本 weui > 1.0.0 不会有该问题
### 解决方案
升级 useExtendedLib 引入的 weui 版本至最新
### 临时绕过方法
通过 npm 模块安装 weui@1.0.0 而不通过 useExtendedLib

**Comment by changjingli** [comment]
目前小程序开发者工具是 最新版，稳定版 Stable 1.03.2005140

请问如何`升级 useExtendedLib 引入的 weui 版本至最新`?

**Comment by beary** [comment]
@Tidyzq `useExtendedLib`引入`weui`时能如何指定版本号？

**Comment by Tidyzq** [comment]
> 目前小程序开发者工具是 最新版
> 
> > 稳定版 Stable 1.03.2005140
> > macOS 10.15.5
> 
> 请问如何`升级 useExtendedLib 引入的 weui 版本至最新`?

@changjingli 需要官方升级，请参考上面的解决方案

> @Tidyzq `useExtendedLib`引入`weui`时能如何指定版本号？

@beary 不能指定，默认使用最新。通过 npm 模块安装可以指定

**Comment by MoonBall** [comment]
使用 1.0.7 版本仍然有 warning。1.0.7 的版本的 checkbox.wxss 文件内容有属性选择器。
![image](https://user-images.githubusercontent.com/13298548/108452157-fd9b1680-72a2-11eb-967c-681d688c7d9b.png)

**Comment by MoonBall** [comment]
@Tidyzq tabbar 组件也会报 warning

**Comment by choicw** [comment]
使用1.0.7版本发现 searchbar组件 warning 具有标签选择器：
![image](https://user-images.githubusercontent.com/48818146/108666730-2594af00-751b-11eb-8639-55f8885aff84.png)
