### ISSUE TITLE
Half Screen Dialog弹窗组件的desc的Slot插槽，组件源码为什么设置在title存在的情况下面不显示

### ISSUE THREAD

**Issue by hyx0217** [wechat-miniprogram/weui-miniprogram#112]
如图，源码21行，不知道为什么要这样设置，看文档试半天出不来，翻看源码才发现这里的判断有点问题。不应该是wx:if=“{{desc}}"吗
![image](https://user-images.githubusercontent.com/45928314/83859974-4466d180-a751-11ea-8960-8919816cd563.png)

**Comment by odayou** [comment]
哈哈，的确有点迷，但是还是得按人家的来啊

**Comment by Tidyzq** [comment]
v1.0.6 修复
