### ISSUE TITLE
navigation-bar 的后退图标怎么设置颜色？

### ISSUE THREAD

**Issue by chenyanbin-dkhs** [wechat-miniprogram/weui-miniprogram#114]
https://developers.weixin.qq.com/miniprogram/dev/extended/weui/navigation.html
有针对标题和背景设置颜色，但是后退图标永远是黑色的，有办法修改吗？ 谢谢 ！

**Comment by Tidyzq** [comment]
暂时没有办法修改，后退图标是 svg 实现的

**Comment by chenyanbin-dkhs** [comment]
> 暂时没有办法修改，后退图标是 svg 实现的

谢谢回复，我后来是通过修改样式来实现
.weui-navigation-bar .bar--weui-navigation-bar__btn_goback{
   mask-image: url('data:image/svg+xml;base64......');
}

**Comment by Tidyzq** [comment]
已解决
