### ISSUE TITLE
页面部分样式与文档不一致

### ISSUE THREAD

**Issue by beary** [wechat-miniprogram/weui-miniprogram#116]
### 表现

`.page__hd`以及`page__title`包裹的文字都贴在页面最左边，与页面没有边距，而且字体也是普通文本字体

### 重现步骤
- 新建初始项目，然后使用`npm`安装的方式安装并构建最新版的`weui-miniprogram`后
- 复制粘贴 https://developers.weixin.qq.com/miniprogram/dev/extended/weui/ 页的任意一个组件示例到页面

### 原因

查看了项目 https://github.com/Tencent/weui-wxss/blob/master/dist 的`app.wxss`，发现`.page__hd`是有声明样式的，但在`node_modules`中查看`weui-miniprogram`目录下的只有`style/weui.wxss`

### 建议

`菜单 -> 工具 -> 构建 npm` 时应保留`weui-wxss/dist`中的`app.wxss`到`miniprogram_npm/weui-miniprogram/weui-wxss`下，这样就能在项目的`app.wxss`中`@import`此样式了

**Comment by Tidyzq** [comment]
app.wxss 中的 page 相关样式仅为示例相关样式，不是组件样式
