### ISSUE TITLE
npm run init 总是提示 weui-miniprogram-master\node_modules\less: Appears to be a git repo or submo

### ISSUE THREAD

**Issue by lisl4github** [wechat-miniprogram/weui-miniprogram#12]
【日志如下】：
npm ERR! path F:\dev\wx-xcx\study\weui-miniprogram-master\node_modules\less
npm ERR! code EISGIT
npm ERR! git F:\dev\wx-xcx\study\weui-miniprogram-master\node_modules\less: Appears to be a git repo or submo
dule.
npm ERR! git     F:\dev\wx-xcx\study\weui-miniprogram-master\node_modules\less
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\dev\NodeJs\node-v8.4.0-win-x86\node-cache\_logs\2019-08-17T17_53_25_690Z-debug.log

**Comment by cunjinli6** [comment]
emmm，是npm install less失败了？

**Comment by cunjinli6** [comment]
通过下载zip的方式，因为下载下来的不是git仓库，所以不能初始化submodule。
可以通过git clone方式把代码clone下来初始化
如果只是使用，可以通过npm下载或者通过[下载页面](https://github.com/wechat-miniprogram/weui-miniprogram)
