### ISSUE TITLE
Cells/Cell中的ext-class不起作用

### ISSUE THREAD

**Issue by Satlantisy** [wechat-miniprogram/weui-miniprogram#124]
想把cells自带背景给去掉 加入ext-class，查看控制台，wxml里有了，但是wxss没有，跟没添加一样。

看了下源码，extClass是放在props里，不应该放在options的externalClass嘛？

**Comment by Satlantisy** [comment]
没有人嘛？

**Comment by Tidyzq** [comment]
需要将 ext-class 的 wxss 声明部分写在 app.wxss 作为全局样式。如果依然不行麻烦提供一下复现代码片段

**Comment by Satlantisy** [comment]
> 需要将 ext-class 的 wxss 声明部分写在 app.wxss 作为全局样式。如果依然不行麻烦提供一下复现代码片段

明白了 多谢！

**Comment by SuniceTop** [comment]
cell 组件的inline 设置了没有效果，class 上没有注入 weui-cell_label-block 这个样式
