### ISSUE TITLE
uploader 组件出现bug

### ISSUE THREAD

**Issue by Mybuhe** [wechat-miniprogram/weui-miniprogram#127]
当上传一张图片后会显示错误,
VM1979:1 Failed to load local image resource /miniprogram_npm/weui-miniprogram/uploader/[object%20Object] 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error)

出现的错误在src/uploader/uploader.ts    148行，我把
                  oldFiles[len + index].url = url;
改成了
                  oldFiles[len + index] = url;
就没有这个问题了
BUG造成的原因是，外层多了一个url
可以的话给我个内推呗，嘻嘻

**Comment by Mybuhe** [comment]
你们改一下呗

**Comment by Satlantisy** [comment]
这里回复的超级慢，还是自己重写一个吧

**Comment by Mybuhe** [comment]
我正在做

**Comment by Mybuhe** [comment]
嗯，看出来了，直接放弃了

**Comment by Tidyzq** [comment]
无法复现该错误，猜测是你的 upload 函数返回的结构不符合 `Promise<{ urls: string[] }>`，如
```javascript
Page({
    ...
    onLoad() {
        this.setData({
            uploadFile: this.uploadFile.bind(this)
        })
    },
    uploadFile(files) {
        return Promise.resolve({ urls: ['http://qq.com/b.png'] })
    }
})
```
```xml
<!-- wxml -->
<mp-uploader upload="{{uploadFile}}" />
```
如无法解决，麻烦提供一下代码片段 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by Tidyzq** [comment]
由于不活跃关闭
