### ISSUE TITLE
icon组件

### ISSUE THREAD

**Issue by Xushd529** [wechat-miniprogram/weui-miniprogram#128]
const getFixedIconType = function (type) {
  // 兼容旧版本 typo
  return type === 'field' ? 'filled' : type;
};
这个兼容是不是有些问题，如下改
return type === 'filled' ? 'field' : type;
xml 中的type都是field 
导致 icon 填充模式显示失败

**Comment by Tidyzq** [comment]
没有太看懂。
这里的的 typo 是：**正确的**拼写应该是 filled，而旧版以及文档**错误地**写成了 field。
而图标数据都是以 filled 和 outline 在 icondata.ts 中区分

**Comment by Tidyzq** [comment]
由于不活跃关闭
