### ISSUE TITLE
Icon 组件无法使用

### ISSUE THREAD

**Issue by spadek-w** [wechat-miniprogram/weui-miniprogram#130]
通过 useExtendedLib 引入WeUI
按官方示例<mp-icon type="field" icon="add" color="black" size="{{25}}"></mp-icon>使用时，显示如下
Cannot read property 'outline' of undefined
TypeError: Cannot read property 'outline' of undefined
或者
Cannot read property 'filled' of undefined
TypeError: Cannot read property 'filled' of undefined

**Comment by Tidyzq** [comment]
无法复现，能否提供一个复现代码片段？
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by spadek-w** [comment]
这个issues好了 可以关了 不好意思  
但是几天前那个时间段确实有以上问题
Cannot read property 'outline' of undefined
TypeError: Cannot read property 'outline' of undefined
以及
Cannot read property 'filled' of undefined
TypeError: Cannot read property 'filled' of undefined
使用方式为
app.json中
```
"useExtendedLib": {
    "weui": true
  },
```
index.json中
```
"mp-icon": "/miniprogram_npm/weui-miniprogram/icon/icon"
```
wxml 使用就会出现 现在好了
