### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by song872229436** [wechat-miniprogram/weui-miniprogram#133]
切换了n个版本的node也不行啊，难道只有我一个会这样？
![image](https://user-images.githubusercontent.com/23710669/91835802-75856e00-ec7c-11ea-9c49-6926e99f7e35.png)
![image](https://user-images.githubusercontent.com/23710669/91835832-8209c680-ec7c-11ea-9982-499e293bb55a.png)

**Comment by Tidyzq** [comment]
不需要执行 `npm run init`
初始化项目直接执行 `npm run submodule && npm i && npm run dev` 即可
