### ISSUE TITLE
mp-grids组件的几个问题

### ISSUE THREAD

**Issue by weixiaoming1981** [wechat-miniprogram/weui-miniprogram#134]
1. 官网上没有mp-grids，只有 mp-cols和mp-rows
2. mp-grids的url不能动态修改，在onLoad中动态修改后，查看html，navigator中的url没有值。

**Comment by anuxs** [comment]
1、mp-grids是这个扩展库自己封装的，跟官网的文档是不同的，看源码就知道的。你想用哪个都可以。我觉得cols和rows比较麻烦，但是很灵活和强大，自己怎么组装都可以。这个grids就是比较简单，都在js里面指定初始化的行列了，自动排版。
