### ISSUE TITLE
useExtendedLib引入的导航栏布局出现了问题？

### ISSUE THREAD

**Issue by oloshe** [wechat-miniprogram/weui-miniprogram#135]
![image](https://user-images.githubusercontent.com/40467840/92231564-7e29ae80-eedf-11ea-972c-ac2de734ff59.png)

**Comment by Tidyzq** [comment]
麻烦提供一个复现代码片段？https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by savokiss** [comment]
刚出现的，weui 组件库 在 iOS 下突然样式就乱了

**Comment by oloshe** [comment]
> 麻烦提供一个复现代码片段？https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

这里不是微信开放社区......(ノへ￣、)

**Comment by Tidyzq** [comment]
> 刚出现的，weui 组件库 在 iOS 下突然样式就乱了

今天刚发布了一个版本，我们先回退试下
