### ISSUE TITLE
项目运行npm run init 报错

### ISSUE THREAD

**Issue by dingxihao1991** [wechat-miniprogram/weui-miniprogram#136]
`D:\wx_workspace\xiaochengxu_workspace\wx_miniProgram\openUI_demo\weui-miniprogram>npm run init

> weui-miniprogram@1.0.5 init D:\wx_workspace\xiaochengxu_workspace\wx_miniProgram\openUI_demo\weui-miniprogram
> npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev

> weui-miniprogram@1.0.5 submodule D:\wx_workspace\xiaochengxu_workspace\wx_miniProgram\openUI_demo\weui-miniprogram
> git submodule init && git submodule update --init

D:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weui-miniprogram@1.0.5 submodule: `git submodule init && git submodule update --init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weui-miniprogram@1.0.5 submodule script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-09-06T10_17_03_009Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weui-miniprogram@1.0.5 init: `npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weui-miniprogram@1.0.5 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-09-06T10_17_03_044Z-debug.log
`

**Comment by Tidyzq** [comment]
https://stackoverflow.com/questions/49256190/how-to-fix-git-sh-setup-file-not-found-in-windows
