### ISSUE TITLE
该项目本地编译生成的demo和官方文档中在线预览的demo不一致

### ISSUE THREAD

**Issue by justable** [wechat-miniprogram/weui-miniprogram#137]
该项目本地编译生成的demo和官方文档中在线预览的demo不一致，我想要参考后者，请问源码哪有？

**Comment by justable** [comment]
原来在miniprogram-demo仓库。

**Comment by frankdou** [comment]
npm run dev会产生`miniprogram_dist`文件夹，本地预览导入该文件夹.....
