### ISSUE TITLE
slideview组件在动态修改按钮属性时无效

### ISSUE THREAD

**Issue by Syahsing** [wechat-miniprogram/weui-miniprogram#138]
**uni-app环境下面动态修改按钮的文字内容无效**

**Comment by Syahsing** [comment]
这个组件经常出现修改按钮名称不生效的问题，修改了多次仍然没有完全解决

**Comment by Tidyzq** [comment]
请提供问题详细说明或复现代码

**Comment by Syahsing** [comment]
我小程序是用uni-app开发的。引入了原生组件slideview，需要为每个引用slideview的行动态修改按钮名称（置顶、取消置顶功能）。但是每次都是由[置顶 -> 取消置顶]变化时按钮名称正常变化。由[取消置顶 -> 置顶]变化时，按钮名称不变。 已经确定，我向buttons传递的值肯定是对的

**Comment by Tidyzq** [comment]
这个问题建议向 uni-app 反馈一下
