### ISSUE TITLE
uploader 的  'sizeType' 'sourceType' 参数不工作

### ISSUE THREAD

**Issue by elvinzhu** [wechat-miniprogram/weui-miniprogram#139]
我看了代码，这俩参数压根没有传递给 `wx.chooseImage

**Comment by Tidyzq** [comment]
已修复过 #80

**Comment by elvinzhu** [comment]
@Tidyzq 哪个分支修复的？master 分支我看代码没有，小程序中这个问题也依然在

**Comment by Tidyzq** [comment]
> @Tidyzq 哪个分支修复的？master 分支我看代码没有，小程序中这个问题也依然在

develop 分支，这周我们尽量发一个新版本
