### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by misTgone** [wechat-miniprogram/weui-miniprogram#147]
## Bug描述
扩展组件sticky无法通过useExtendLib引用；其次，通过npm方式，发现没有sticky这个组件了
## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :
"useExtendedLib": {
    "weui": true
  }

**Comment by Tidyzq** [comment]
拓展组件在 https://github.com/wechat-miniprogram/miniprogram-component-plus
