### ISSUE TITLE
需要官方提供一下 weui-miniprogram 的 types 定义文件

### ISSUE THREAD

**Issue by anuxs** [wechat-miniprogram/weui-miniprogram#148]
## 遇到的问题
我使用的是 TypeScript开发，使用weui-miniprogram组件时需要自己写组件类型定义非常麻烦，部分组件还不知道怎么写 types 定义，容易错。既然 weui-miniprogram 使用 TS 开发的，能否直接提供一份 types.d.ts 文件？

## 特性方案
希望官方能够提供 weui-miniprogram  的 types.d.ts 文件，非常感谢。

**Comment by Tidyzq** [comment]
在什么场景下使用 weui 必须要提供 d.ts ? 因为在小程序原生下通过 json 的 usingComponents 导入组件，本身是和 ts 类型割裂的，也就是不需要 d.ts

**Comment by anuxs** [comment]
> 在什么场景下使用 weui 必须要提供 d.ts ? 因为在小程序原生下通过 json 的 usingComponents 导入组件，本身是和 ts 类型割裂的，也就是不需要 d.ts

remax 下面用，虽然有偷懒的做法，但是还是想code 的时候精确的获得类型提示。
