### ISSUE TITLE
表单组件在 dark 模式下，点击态颜色错误

### ISSUE THREAD

**Issue by yadigithub** [wechat-miniprogram/weui-miniprogram#149]
`                <mp-cell prop="mobile" title="手机号" ext-class="weui-cell_vcode">
                    <input bindinput="formInputChange" data-field="mobile" class="weui-input" placeholder="请输入手机号" />
                    <button slot="footer" type="default" class="weui-vcode-btn">获取验证码</button>
                </mp-cell>
`

在 dark 模式下，按钮点击态的颜色仍然是 light 模式下的亮色。

**Comment by Tidyzq** [comment]
经确认是 weui-wxss 使用了固定色值

https://github.com/Tencent/weui-wxss/blob/21a3072be6b4ff57f7ed3a2ab7ecd6b6eb628b83/src/style/widget/weui-cell/weui-form/weui-vcode.less#L49

issue 转移至 weui-wxss 仓库
