### ISSUE TITLE
[BUG]errorChanged is not defined

### ISSUE THREAD

**Issue by strangebank** [wechat-miniprogram/weui-miniprogram#153]
## Bug描述
errorChanged
<img width="850" alt="WX20210123-202133@2x" src="https://user-images.githubusercontent.com/5893333/105578090-bc553b00-5db8-11eb-9e2e-81161310067e.png">

## 版本信息
- weui-miniprogram 1.0.7
https://www.npmjs.com/package/weui-miniprogram

**Comment by gentlelynn** [comment]
翻看源码，在src/form/form-validator.ts文件我们可以找到，当验证参数只有cb时（validate(cb?: any)方法）即我们表单什么都没有填的这种情况下，errorChanged确实是没有定义，而是直接调用的（没有仔细看为啥注释掉了原本的let定义，也许只是不想给errorChanged直接赋值为false）。但是到后面有值验证时（ validateField(name, value, cb?)），它是定义了的。
