### ISSUE TITLE
按文档命令执行无法通过？

### ISSUE THREAD

**Issue by weizuichunsun** [wechat-miniprogram/weui-miniprogram#16]
![image](https://user-images.githubusercontent.com/27394381/63662986-39126d00-c7f3-11e9-9dcf-ef4a1662d5d4.png)

**Comment by cunjinli6** [comment]
通过下载zip的方式，因为下载下来的不是git仓库，所以不能初始化submodule。
可以通过git clone方式把代码clone下来初始化
如果只是使用，可以通过npm下载或者通过[下载页面](https://github.com/wechat-miniprogram/weui-miniprogram)
