### ISSUE TITLE
[BUG]navbar weui-tab__content 不显示

### ISSUE THREAD

**Issue by xjcloudy** [wechat-miniprogram/weui-miniprogram#160]
## Bug描述
新人，求指教。一开始，是使用 demo 里面的代码。在我的项目中调试。发现 content 中的内容始终不显示。通过调试 发现。 `weui-tab__content` 的默认 wsxx 样式 是 `dsiplay:none`。 而 通过hidden 来控制 不起作用。 在社区里提了问题。没有得到 回复。
隔天，我干脆 clone 了 demo 的代码。在本地 跑起来，发现一样的问题。干脆 就 提个issue 吧。
## 复现方式
https://developers.weixin.qq.com/community/develop/doc/000a860803c0a8b9fadb32a1f56000?fromCreate=0
## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :useExtendedLib

**Comment by Tidyzq** [comment]
感谢反馈。这个 example/navbar 页面其实已经废弃了。正确的使用方式应该是:
```xml
<view class="weui-tab__content" style="display: {{activeIndex === 0 ? 'block' : 'none'}}">选项一的内容</view>
<view class="weui-tab__content" style="display: {{activeIndex === 1 ? 'block' : 'none'}}">选项二的内容</view>
<view class="weui-tab__content" style="display: {{activeIndex === 2 ? 'block' : 'none'}}">选项三的内容</view>
```
