### ISSUE TITLE
微信开发者工具上传代码时会做tree shaking吗？

### ISSUE THREAD

**Issue by Jim-Rae** [wechat-miniprogram/weui-miniprogram#17]
我直接把整个miniprogram_dist文件夹添加到小程序工程里使用，我想请问一下微信开发者工具上传代码时会做tree shaking吗？就是会把未引用的组件代码去除掉吗？
还有我看到miniprogram_dist文件夹里的组件文件夹的js文件都包含有webpack打包的代码，请问这些代码的作用是什么呢？
![image](https://user-images.githubusercontent.com/25401068/63706708-b32e0a80-c862-11e9-95f0-3a9645b68668.png)

**Comment by cunjinli6** [comment]
1. 工具不会做tree shaking，目前可以通过页面[下载](https://developers.weixin.qq.com/miniprogram/dev/extended/weui/download.html)你需要的组件
2. 目前dist经过webpack打包，会带一些webpack的构建代码。
