### ISSUE TITLE
npm安装组件库，构建weui-miniprogram目录没有weui-wxss目录[BUG]

### ISSUE THREAD

**Issue by changhuaC** [wechat-miniprogram/weui-miniprogram#179]
## Bug描述
按照文档“@import 'weui-miniprogram/weui-wxss/dist/style/weui.wxss';”引用全局样式，报错，找不到weui.wxss
后发现构建后的weui-miniprogram根本没有weui-wxss文件夹

## 复现方式
项目根目录安装npm install weui -save --production
编译出错，“File not found: /miniprogram_npm/weui-miniprogram/weui-wxss/dist/style/weui.wxss”

## 版本信息
"weui-miniprogram": "^1.1.0":

**Comment by lazyou** [comment]
我也是

**Comment by Ronald9** [comment]
TX 的大哥们。麻烦认真点好吗。。。
