### ISSUE TITLE
[问题]文档挂了

### ISSUE THREAD

**Issue by Traeyee** [wechat-miniprogram/weui-miniprogram#180]
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/extended/weui/
文档地址指向github，github又指回这个地址，死循环了都。前阵子还在的，应该是最近改页面改没的

**Comment by PinBoLei** [comment]
同问，最近没怎么看，今天一看没有了

**Comment by zhengmenghuang** [comment]
同找文档

**Comment by chen9091** [comment]
文档怎么没看到，官网让跳github,github让跳官网

**Comment by guanpengchn** [comment]
文档哪儿去了？

**Comment by oyghdit** [comment]
同问

**Comment by tennessine** [comment]
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/extended/weui/
这个叫文档？开眼界了

**Comment by zobx** [comment]
没人管吗。。

**Comment by llh1187** [comment]
令人窒息

**Comment by yonghua4413** [comment]
屁股挨了一刀，真开了眼啊

**Comment by Traeyee** [comment]
后面发现文档藏在这https://github.com/wechat-miniprogram/weui-miniprogram/tree/master/docs

**Comment by mountainmoon** [comment]
KPI 开源项目，呵呵

**Comment by Tidyzq** [comment]
文档迁移至 https://wechat-miniprogram.github.io/weui/docs/
