### ISSUE TITLE
[BUG] 一些警告官方处理一下

### ISSUE THREAD

**Issue by mazhewei** [wechat-miniprogram/weui-miniprogram#184]
## Bug描述
描述你遇到的Bug，所产生的非预期行为
[Component] the type of property "search" is illegal (when preparing behavior "miniprogram_npm/weui-miniprogram/searchbar/searchbar").
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/weui-miniprogram/checkbox/checkbox.wxss:1:79)

## 复现方式
复现该Bug的方式，建议直接提供 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
新建工程后，引入weui （useExtendedLib 方式）
在page.json 导入相关组件即可复现

## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :
- useExtendedLib
- 基础库版本：2.19.4

**Comment by hmwdt** [comment]
I had the same problem

**Comment by Tidyzq** [comment]
fixed

**Comment by liu12151407** [comment]
同样的Bug，时隔两年，仍然还存在
