### ISSUE TITLE
[BUG] example里面的图片如png是不是有问题？

### ISSUE THREAD

**Issue by zhangdaren** [wechat-miniprogram/weui-miniprogram#188]
## Bug描述
如题 。。。。。。打不开哇，，显示文件有问题。

## 复现方式
复现该Bug的方式，建议直接提供 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)

## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :

**Comment by Tidyzq** [comment]
已修复
