### ISSUE TITLE
[BUG]mp-tabbar view.weui-tabbar.tabbar--weui-tabbar?

### ISSUE THREAD

**Issue by zhouted** [wechat-miniprogram/weui-miniprogram#189]
## Bug描述
weui-tabbar在ipad下显示不正常：跑到了侧边且width变为只有60px。
在ipad真机调试发现，#shadow-root下的根view标签其class="weui-tabbar tabbar--weui-tabbar"，即比在开发工具下看到的多了"tabbar--weui-tabbar"这个类，这个多出的类样式重设了flex-direction、height和width等导致tabbar显示错位。
奇怪的是，查遍源码没有找到设置和定义"tabbar--weui-tabbar"这个类的地方。

## 复现方式
&lt;mp-tabbar&nbsp;class=&quot;tabbar&quot;&nbsp;list=&quot;{{bars}}&quot;&nbsp;current=&quot;{{barIndex}}&quot;&nbsp;bindchange=&quot;onNavbarChange&quot;&gt;&lt;/mp-tabbar&gt;

## 版本信息
- weui 版本 v2.4.0

**Comment by Tidyzq** [comment]
https://github.com/wechat-miniprogram/weui-miniprogram/blob/master/src/components/tabbar/tabbar.less

这个是预期行为。已在新版添加 reactive 属性，可通过 `<mp-tabbar reactive="{{false}}">`关闭
