### ISSUE TITLE
[BUG]官网文档，部分链接失效

### ISSUE THREAD

**Issue by fengrui358** [wechat-miniprogram/weui-miniprogram#197]
## Bug描述
官网文档，部分链接失效

## 复现方式
官网 <https://wechat-miniprogram.github.io/weui/docs/quickstart.html> 

引入组件 `useExtendedLib 扩展库` 的链接地址 <https://wechat-miniprogram.github.io/weui/docs/reference/configuration/app.html#useExtendedLib> 打不开

**Comment by daxiajunjun** [comment]
这文档写的真的是气死人，每次看文档都要口吐芬芳；

**Comment by daxiajunjun** [comment]
@Tidyzq

**Comment by Lsnsh** [comment]
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#useExtendedLib

在小程序文档里找到了，对应的应该是这个链接，可能需要改成绝对路径。

**Comment by Tidyzq** [comment]
fixed
