### ISSUE TITLE
[BUG] 快速上手，引用方式1 内容好像挂了。

### ISSUE THREAD

**Issue by Jiujiale** [wechat-miniprogram/weui-miniprogram#209]
https://wechat-miniprogram.github.io/weui/docs/quickstart.html#%E4%BD%BF%E7%94%A8%E4%B9%8B%E5%89%8D
## Bug描述
WeUI 文档问题

## 复现方式
![image](https://user-images.githubusercontent.com/15116421/180376095-0ed55b85-e67b-4c70-adf0-69d77d5a4bc6.png)
![image](https://user-images.githubusercontent.com/15116421/180376133-4ef9dfb8-f0e5-4a45-8fe0-8743a8832e25.png)

## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :

**Comment by Tidyzq** [comment]
fixed

**Comment by Jiujiale** [comment]
重新定义fixed。 @Tidyzq 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/15116421/206988956-f6a7f501-df9e-4658-a7a9-3d2f7e42b393.png">
