### ISSUE TITLE
[FEATURE] weui示例小程序的扩展组件里有一个 tabs 组件，代码好像没有找到？

### ISSUE THREAD

**Issue by iibrat** [wechat-miniprogram/weui-miniprogram#213]
## 遇到的问题
weui示例小程序的扩展组件里有一个 tabs 组件，代码好像没有找到？

## 特性方案
weui示例小程序的扩展组件里有一个 tabs 组件，代码好像没有找到？

**Comment by Tidyzq** [comment]
here it is ~
https://github.com/wechat-miniprogram/miniprogram-component-plus/blob/master/src/tabs/index.wxml
