### ISSUE TITLE
[BUG] mp-dialog组件在iphone11及以上机型中，出现不弹窗问题

### ISSUE THREAD

**Issue by honxinn** [wechat-miniprogram/weui-miniprogram#219]
## Bug描述
小程序登录之后会有一个异常弹窗，在iphone11及以上机型中不会弹出，测试过8P、XR、11、12、13、14

## 复现方式
小程序登录之后，检测用户状态异常，弹出mp-dialog弹窗，并未弹出，iphone11及以上机型必现
## 版本信息
- useExtendedLib

**Comment by sonyta** [comment]
问一下这个怎么解决的？ @honxinn
