### ISSUE TITLE
使用npm的方式，如何引入weui.wxss

### ISSUE THREAD

**Issue by scutcl** [wechat-miniprogram/weui-miniprogram#22]
app.wxss中
@import "./weui-miniprogram/weui-wxss/dist/style/weui.wxss";
报错 File not found

**Comment by saoraozhe3hao** [comment]
<style src="../node_modules/weui-miniprogram/miniprogram_dist/weui-wxss/dist/style/weui.wxss"></style>

**Comment by cunjinli6** [comment]
npm的方式，试下`@import './miniprogram_npm/weui-miniprogram/weui-wxss/dist/style/weui.wxss';`
