### ISSUE TITLE
weui 文档上的组件比 weui 小程序组件展示的还要少

### ISSUE THREAD

**Issue by dong-lufei** [wechat-miniprogram/weui-miniprogram#229]
## 遇到的问题
 weui 小程序实例展示了9个扩展组件 video-swiper、tabs、recycle-view 等等，但是 WeUI组件库简介文档里没有这些介绍和使用方式。

## 特性方案
 希望完善 WeUI 组件库文档对扩展组件和多端适配组件的介绍

**Comment by YQjiuhao** [comment]
这里面有讲的:http://www.starry.wiki/

**Comment by qmjy** [comment]
组件希望还是可以继续完善起来。

**Comment by Tidyzq** [comment]
https://github.com/wechat-miniprogram/miniprogram-component-plus
