### ISSUE TITLE
[BUG] mp-half-screen-dialog组件和mp-actionsheet打开时位置异常

### ISSUE THREAD

**Issue by honxinn** [wechat-miniprogram/weui-miniprogram#233]
## Bug描述
现象如下图，在真机调试过程中，确定弹窗定位是在bottom为0的地方，修改bottom为正整数，弹窗定位上升，感觉是小程序弹窗的页面被识别往上了50%，IOS下必现，安卓部分设备必现，开发者工具没这个问题，小程序中所有的mp-half-screen-dialog，mp-actionsheet都有这个问题

![image](https://github.com/wechat-miniprogram/weui-miniprogram/assets/49867035/76f765dd-ea46-4e26-82ca-99252c3309f4)
![image](https://github.com/wechat-miniprogram/weui-miniprogram/assets/49867035/7cd8dc86-4cb4-4490-983a-d156a52ffb15)

## 复现方式
没有什么特别的，没有改任何样式
`<mp-half-screen-dialog show="{{isOpen}}" closabled="{{false}}" ext-class="mpicker" maskClosable="{{false}}">`

 ` <view class="mpicker-title" slot="title" catchtouchmove>`

  `  <button class="mpicker-cancel" bindtap="handleCancel">取消</button>`

`    <view>请选择</view>`

`    <button class="mpicker-ok" bindtap="handleOk">确定</button>`

`  </view>`

`  <scroll-view slot="desc" scroll-y>`

`    xxx`

`  </scroll-view>`

`</mp-half-screen-dialog>`

## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] : useExtendedLib

**Comment by Tidyzq** [comment]
建议将弹窗组件如 `dialog` 和 `half-screen-dialog` 都放到页面最高层级试试。如果还不行可以提供下复现代码片段

**Comment by honxinn** [comment]
已解决
