### ISSUE TITLE
[BUG]Half Screen Dialog半屏弹窗组件顶部title有黄色的边框

### ISSUE THREAD

**Issue by xiesantao** [wechat-miniprogram/weui-miniprogram#234]
## Bug描述
描述你遇到的Bug，所产生的非预期行为
Half Screen Dialog半屏弹窗组件顶部title有黄色的边框
## 复现方式
复现该Bug的方式，建议直接提供 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
扫weui的在线预览码头部标题出现黄色边框，我们的项目前年开发的，现在这个组件也出现了
![微信图片_20230810174350](https://github.com/wechat-miniprogram/weui-miniprogram/assets/40421986/1c33ccc6-509b-4d9b-9c56-5e3405d1f5ca)
<img width="277" alt="Snipaste_2023-08-10_17-47-15" src="https://github.com/wechat-miniprogram/weui-miniprogram/assets/40421986/207108a5-c725-4738-bda2-c9dd44459513">

## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :

**Comment by Tidyzq** [comment]
已修复
https://github.com/wechat-miniprogram/weui-miniprogram/commit/91ac994102f4bd12bbf0c45238b3bf8edeb7733d
