### ISSUE TITLE
[BUG] skyline 渲染模式啥时候能兼容下？

### ISSUE THREAD

**Issue by TLovers** [wechat-miniprogram/weui-miniprogram#244]
## Bug描述
描述你遇到的Bug，所产生的非预期行为
无
## 复现方式
复现该Bug的方式，建议直接提供 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
wu
## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :
无

**Comment by Tidyzq** [comment]
1.5.0 已兼容 skyline

**Comment by agulado** [comment]
> 1.5.0 已兼容 skyline

@Tidyzq 我这边看还是有问题，帮忙看下～ #253
