### ISSUE TITLE
扩展组件在哪啊

### ISSUE THREAD

**Issue by 812781385** [wechat-miniprogram/weui-miniprogram#246]
我用手机扫码打开小程序，看到有个扩展组件，里面有很多内容，包括“index-list”这个组件，可是有关文档都没有说明这个组件，请问我该怎么使用这个组件？

**Comment by Tidyzq** [comment]
在这里 https://github.com/wechat-miniprogram/miniprogram-component-plus/tree/master/src/index-list

**Comment by 812781385** [comment]
我写了个使用index-list的文档：
https://blog.csdn.net/qq_40279232/article/details/139503933?spm=1001.2014.3001.5502
