### ISSUE TITLE
[Bug] mp-slideview 显示按钮的动画时长 duration 计算错误

### ISSUE THREAD

**Issue by wiky** [wechat-miniprogram/weui-miniprogram#247]
https://github.com/wechat-miniprogram/weui-miniprogram/blob/5ba58d428d2b68c109420b5f1edb9d87d603ed52/src/components/slideview/slideview.wxs#L210

上面应该是 `showButtons(ins, ownerInstance, st.duration)`，应该是`showButtons(ins, ownerInstance, st.duration / 1000)`

showButtons中使用的参数 withDuration 的单位是 s，st.duration 的单位是 ms。

下面是正确传参的地方，这里的duration是st.duration/1000计算所得，所以调用正确。
https://github.com/wechat-miniprogram/weui-miniprogram/blob/5ba58d428d2b68c109420b5f1edb9d87d603ed52/src/components/slideview/slideview.wxs#L104

**Comment by TLovers** [comment]
这个组件计算宽度的时候还有一个问题，就是当父组件开启root-portal时，右侧滑块区域宽度直接计算为0了
