### ISSUE TITLE
[BUG]commit 798ac7b修改了externalClasses之后ext-class的类名添加与预期不符

### ISSUE THREAD

**Issue by yaime** [wechat-miniprogram/weui-miniprogram#255]
## Bug描述
描述你遇到的Bug，所产生的非预期行为
2024.11.14观察到线上的ios机型及模拟器仍然使用ext-class，添加在元素上的方式仍然为
![image](https://github.com/user-attachments/assets/22d2c76d-9c24-48ed-a003-12a8a6302771)
但是安卓机上的部分的结构为
![image](https://github.com/user-attachments/assets/9a907a60-ca9d-443b-9e2b-0ce56c55c4d2)
这导致我需要选择比如weui-dialog__bd这个class时额外增加另一个component--{{extClass}}这样的选择器
期望改回之前的模式，现在这样并不友好而且文档中没有标注清楚

## 复现方式
复现该Bug的方式，建议直接提供 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
代码片段如下
https://developers.weixin.qq.com/s/OmzgrHmJ7gVm

## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :
- useExtendedLib

**Comment by yaime** [comment]
好像并不是这个修改导致的，我尝试用老版本仍然可以复现这个问题， 这种情况是基础库那面出现问题了么？

**Comment by Tidyzq** [comment]
你好，麻烦提供一个复现问题的代码片段，以方便复现问题

**Comment by Tidyzq** [comment]
你好，你的代码片段是预期 【这里的内容应该没问题】这段文字不应该展示是么？

看起来是符合 ext-class 这个修改的改动期望行为，因为以前的 ext-class 行为不符合预期。

因为小程序的自定义组件是样式隔离的，默认声明在自定义组件内的元素（wxml 中的 class）只能被自定义组件的样式（wxss ）影响。具体隔离规则可以参考 [文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB)。

具体到你提供的这个代码片段，`db-11` 这个 class 在 custom-component 这个自定义组件中使用，而 `custom-component.wxss` 文件中没有 `db-11` 相关的样式，因此无法命中样式。

要让你的代码片段符合预期，有两种方式：
1. 将 `db-11` 相关的样式从 `index.wxss` 移动到 `custom-component.wxss` 中。
2. 为 `custom-component` 自定义组件的 `custom-component.json` 中声明 `"styleIsolation": "apply-shared"`，从而允许 `custom-component` 自定义组件应用页面全局样式。

**Comment by yaime** [comment]
> 你好，你的代码片段是预期 【这里的内容应该没问题】这段文字不应该展示是么？
> 
> 看起来是符合 ext-class 这个修改的改动期望行为，因为以前的 ext-class 行为不符合预期。
> 
> 因为小程序的自定义组件是样式隔离的，默认声明在自定义组件内的元素（wxml 中的 class）只能被自定义组件的样式（wxss ）影响。具体隔离规则可以参考 [文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB)。
> 
> 具体到你提供的这个代码片段，`db-11` 这个 class 在 custom-component 这个自定义组件中使用，而 `custom-component.wxss` 文件中没有 `db-11` 相关的样式，因此无法命中样式。

这个解释是行不通的，具体证明代码片段https://developers.weixin.qq.com/s/jSv3VIm67bVW 
可以注意到代码中的
1. components/custom-component-in-page 在iOS和模拟器是可以正常展示的，在安卓目前不行，这是我提出的问题。
1. components/custom-component-in-file 这是为了回复你刚才的解决方案，我将.in-file .weui-dialog__bd 放在了custom-component-in-file.wxss中，这个做法在三端均没有正常展示。
我理解mp-dialog这个组件的mp-dialog.json中已经定义了"styleIsolation": "apply-shared" 这个属性，可以理解他们在iOS和模拟器上的行为，但是安卓上的这个情况还是不太对。

我也尝试了将未改版之前的mp-dialog直接放在文件里引用发现也是同1一样的情况，是否是小程序基础库产生的问题呢

**Comment by Tidyzq** [comment]
fixed in 24e453476a05f53befd09f10644554264ec4565e

**Comment by jianatrm** [comment]
> [已在24e4534](https://github.com/wechat-miniprogram/weui-miniprogram/commit/24e453476a05f53befd09f10644554264ec4565e)中修复[](https://github.com/wechat-miniprogram/weui-miniprogram/commit/24e453476a05f53befd09f10644554264ec4565e)


<img width="755" alt="image" src="https://github.com/user-attachments/assets/2493ecec-63d8-46cd-b9a7-7c45d8f7785b">
这么大的改动你们都不考虑线上版本使用情况吗，不经过验证就随意上线吗。能不能负责一点。智障行为
