### ISSUE TITLE
path `weui-miniprogram/weui-wxss/dist/style/weui.wxss` not found from `./app.wxss`.

### ISSUE THREAD

**Issue by 745740681** [wechat-miniprogram/weui-miniprogram#256]
## Bug描述
描述你遇到的Bug，所产生的非预期行为
![image](https://github.com/user-attachments/assets/b70f4d84-a6bc-4e21-bc53-851a09172118)
反正就挺奇怪的，开始的时候用uni-app使用weui 组件库报这个错误。后来用小程序开发工具也报这个错误。按照官网一步一步操作也会有问题。
## 复现方式
复现该Bug的方式，建议直接提供 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
复现  百分之百会复现 引入就会有问题
## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :

**Comment by Tidyzq** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
点击开发者工具中的菜单栏：工具 --> 构建 npm

**Comment by fewbadboy** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html 点击开发者工具中的菜单栏：工具 --> 构建 npm

稳定版，清理缓存 重新 构建 npm,  同样的问题
[代码依赖分析] 找到 1 个依赖异常情况，可能会导致对应文件无法加载，请检查。
Couldn't resolve the Wxss file "weui-miniprogram/weui-wxss/dist/style/weui.wxss" relative to "/app.wxss`:0:0`"

**Comment by Tidyzq** [comment]
已修改文档为 `@mport '/miniprogram_npm/weui-miniprogram/weui-wxss/dist/style/weui.wxss';`
