### ISSUE TITLE
[FEATURE] 什么时候 skyline 渲染模式下可以使用 useExtendedLib 来引入？

### ISSUE THREAD

**Issue by jaggerwang** [wechat-miniprogram/weui-miniprogram#257]
## 遇到的问题
使用 npm 引入比较麻烦，并且安装时还报错了，对于新手上手门槛较高。

## 特性方案
跟 webview 一样，可以简单使用 useExtendedLib 来引入。

**Comment by Tidyzq** [comment]
npm 引入已经支持了，useExtendedLib 由于更新会影响所有线上小程序，目前正在缓慢灰度中。

建议先用 npm 引入试试，提早发现问题也有助于灰度进度。
