### ISSUE TITLE
[BUG] Tabbar 组件首次打开 Tab 页之后，需要连续两次点击来切换 Tab，选中状态才正确。

### ISSUE THREAD

**Issue by jaggerwang** [wechat-miniprogram/weui-miniprogram#260]
## Bug描述
一共三个 Tab 页，每个 Tab 页 current 其实是固定的，分别为 0、1、2，通过 wx.switchTab() 切换页面时，首次切到某个 Tab 页时 Tabbar 图标选中状态是对的，但第二次切到该 Tab 时（也就是页面已经加载过），页面切换过去了，但图标选中状态是其它页面的，比如第二次切换到 Tab 1，但选中状态是 Tab 2 的图标。

## 复现方式

_home.wxml_
```xml
<view class="page">
  <mp-navigation-bar title="知识" back="{{false}}" background="{{navigationBar.background}}" color="{{navigationBar.color}}"></mp-navigation-bar>

  <scroll-view scroll-y class="body">
    知识
  </scroll-view>

  <mp-tabbar list="{{tarbarTabs}}" current="{{0}}" bind:change="onTabbarChange"></mp-tabbar>
</view>
```

_home.ts_
```typescript
Page({
  behaviors: [tabbarBehavior],
});
```

_tabbarBehavior.ts_
```typescript
export default Behavior({
  data: {
    tarbarTabs: [
      {
        text: "首页",
        pagePath: "/pages/home/home",
        iconPath: "/static/icons/home.svg",
        selectedIconPath: "/static/icons/home-fill.svg",
        badge: 0,
      },
      {
        text: "知识",
        pagePath: "/pages/knowledge/knowledge",
        iconPath: "/static/icons/book-open.svg",
        selectedIconPath: "/static/icons/book-open-fill.svg",
        badge: 0,
      },
      {
        text: "我的",
        pagePath: "/pages/me/me",
        iconPath: "/static/icons/me.svg",
        selectedIconPath: "/static/icons/me-fill.svg",
        badge: 0,
      },
    ],
  },
  methods: {
    onTabbarChange(e: WechatMiniprogram.CustomEvent) {
      const { item } = e.detail;
      wx.switchTab({ url: item.pagePath });
    },
  },
});

```

后面只有在 tabbarBehavior 里增加一项数据 tarbarSelectedTab 来控制当前 Tab，并在每个 Tab 页的 onShow() 里强行更新该数据为当前页面的 Tab 序号才解决了。

## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] : useExtendedLib

**Comment by Tidyzq** [comment]
你好，这个我理解是小程序 tabbar 的使用问题，而不是组件本身的问题。

小程序一般 tabbar 实现有两种方式：
1. 每个页面绘制一个 tabbar，这种方式只需要你每个页面的 tabbar current 设置为当前页面的下标即可。
2. 结合[自定义 tabbar ](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html) 一起使用，这种方式需要在每个 tab 页都通知 tabbar 改变当前的 current 。

 weui 的 tabbar 组件实际是设计为方式 2 来使用的，所以会在 bind:change 触发的时候自动设置 current 值。我看你这里是希望使用方式 1 来实现，那么其实也不需要在 onShow 里强制更新 current，只需要确保在 bind:change 触发以后通过 setData 再将 current 的值重新覆盖成当前的页面即可。

**Comment by jaggerwang** [comment]
没看明白方式 2，WeUI Tabbar 如何在多个页面共享一个实例，WebView 渲染引擎下每个页面都会创建一个 WebView 实例，肯定没法共享同一个实例。如果是方式 1，在 bind:change 需要执行 switchTab 来切换页面，这个时候执行 setData 没有意义，因为只能改变当前页面的 current，照理来说页面切换时也不需要更新 current，因为每个页面的 current 都是固定的。并且上面的问题中，第一次切换都是 OK 的，只是第二次切换就不对了，比如三个 Tab 1、2、3，初始 Tab 为 1，依此切换到 2、3 没有问题，再切换到 1 就不对了。

**Comment by Tidyzq** [comment]
WebView 渲染引擎下每个页面都会创建一个 WebView 实例，肯定没法共享同一个实例
===========

**Comment by Tidyzq** [comment]
> WebView 渲染引擎下每个页面都会创建一个 WebView 实例，肯定没法共享同一个实例。

自定义 Tabbar 在逻辑层是复用同一个实例，在逻辑层的修改会同步到所有的渲染页面。

> 照理来说页面切换时也不需要更新 current，因为每个页面的 current 都是固定的。

tabbar 组件在点击时会设置自身的 current，所以不是固定的。https://github.com/wechat-miniprogram/weui-miniprogram/blob/master/src/components/tabbar/tabbar.ts#L27
