### ISSUE TITLE
添加组件需求

### ISSUE THREAD

**Issue by weizuichunsun** [wechat-miniprogram/weui-miniprogram#28]
期望组件。
1、拖动排序组件
2、类似微信右上角 + 号点击弹出的冒泡菜单（发起群聊，添加朋友，扫一扫。。。）
3、局部上下刷新组件

**Comment by cunjinli6** [comment]
3. 是在scroll-view里面的下拉刷新？

**Comment by weizuichunsun** [comment]
scroll-view 里面的局部刷新

**Comment by cunjinli6** [comment]
这个需求我们会在基础库里面支持。

**Comment by wechat-miniprogram-admin** [comment]
自定义下拉刷新已经在 scroll-view组件中支持；
拖动排序组件后续会支持上
