### ISSUE TITLE
表单equalTo相等校验始终校验不通过

### ISSUE THREAD

**Issue by Zhang-Shaoqiang** [wechat-miniprogram/weui-miniprogram#29]
<mp-form id="form" rules="{{rules}}" models="{{formData}}">
  <mp-cells>
    <mp-cell prop="password" ext-class="">
      <input bindinput="formInputChange" data-field="password" type="password" class="weui-input" placeholder="请输入新密码" />
    </mp-cell>
    <mp-cell prop="confirm" ext-class="">
      <input bindinput="formInputChange" data-field="confirm" type="password" class="weui-input" placeholder="请再次输入密码" />
    </mp-cell>
  </mp-cells>
</mp-form>

rules: [{ // 多个规则
      name: 'password',
      rules: [{
        required: true,
        message: '请输入密码'
      }, {
        minlength: 6,
        message: '请输入最少6位长度的密码'
      }],
    }, { // 多个规则
      name: 'confirm',
      rules: [{
        required: true,
        message: '请再次输入密码'
      }, {
        equalTo: 'password',
        message: '两次输入密码不一致'
      }],
    }]

**Comment by cunjinli6** [comment]
v0.1.9 fixed
