### ISSUE TITLE
希望添加 drawer 组件

### ISSUE THREAD

**Issue by dkvirus** [wechat-miniprogram/weui-miniprogram#3]
drawer 组件：抽屉组件

支持上下左右四个方向划出。

左边划出场景：小说目录

![image](https://user-images.githubusercontent.com/29170168/61600590-f8f42380-ac63-11e9-84e2-b96d98347057.png)

下边划出场景：电商网站选择规格

![image](https://user-images.githubusercontent.com/29170168/61600599-05787c00-ac64-11e9-88bf-301d13644534.png)

**Comment by cunjinli6** [comment]
应该是2个组件，目前已经在规划中。

**Comment by cunjinli6** [comment]
左滑drawer组件，不是会和小程序左滑返回的手势冲突吗？

**Comment by cunjinli6** [comment]
底部弹起的组件，在v0.2支持

**Comment by Syahsing** [comment]
> 左滑drawer组件，不是会和小程序左滑返回的手势冲突吗？

系统左滑返回都是从屏幕边界开始的
