### ISSUE TITLE
searchbar无法清除搜索结果？

### ISSUE THREAD

**Issue by dontcallmilanac** [wechat-miniprogram/weui-miniprogram#34]
文档中只写不断调用search更新结果，但尝试resolve([])不能清除搜索结果。求解决

**Comment by cunjinli6** [comment]
不能清除搜索结果未能复现，可以贴下你的[代码](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)我看下

**Comment by dontcallmilanac** [comment]
> 不能清除搜索结果未能复现，可以贴下你的[代码](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)我看下

多谢回复，[代码片段在此](https://developers.weixin.qq.com/s/7Qt0vBmi74bu)

**Comment by cunjinli6** [comment]
你是点击input右侧的x无法清除搜索结果吗？

**Comment by dontcallmilanac** [comment]
> 你是点击input右侧的x无法清除搜索结果吗？

是的，点×调用search方法，传入空字符串
