### ISSUE TITLE
表单验证问题：required: false 失效、无法验证空数组

### ISSUE THREAD

**Issue by Grs24** [wechat-miniprogram/weui-miniprogram#36]
- 表单验证会忽略required: false
例：手机号验证写了 mobile: true, 由于需求手机号不是必填，所以加多了条required: false，
但验证结果依然会出现手机号必填。

//手机号校验
{
name: 'mobile',
rules: [{
  required: false,
  message: '选填'
}, {
  mobile: true,
  message: "请填写正确的手机号"
}],
}, 
-  无法判断空数组，会跳过数组的验证
例：无法验证复选框选择状态

**Comment by cunjinli6** [comment]
可以手动写validator验证手机号。

**Comment by cunjinli6** [comment]
v0.2版本已修复required为false的情况
