### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by hong4cong** [wechat-miniprogram/weui-miniprogram#37]
Error: File not found with singular glob: /Users/XX/WeChatProjects/weui-miniprogram/src/weui-wxss/dist/style/weui.wxss (if this was purposeful, use `allowEmpty` option)

**Comment by cunjinli6** [comment]
npm run init跑了么？

**Comment by cunjinli6** [comment]
src/weui-wxss是一个submodule来的，必须要更新下来先。

**Comment by Grs24** [comment]
原来是要先npm run init ，建议把这个步骤也加上使用方法那，不然可能很多人都不知道要先npm run init就npm install了

**Comment by wz-xwg** [comment]
我也遇到了类似的问题， 我是fork到自己的仓储进行操作的。后来看这个评论里说因为有子模块需要 npm run init 我试过之后还是报错。 索性重新clone了这个项目的地址。
克隆时递归了子模块  --recursive。
之后按顺序 执行了：
npm run init
npm install
npm run dev  

现在项目已经跑起来了。

**Comment by chengkaii** [comment]
> src/weui-wxss是一个submodule来的，必须要更新下来先。

跑了也还是报错

![image](https://user-images.githubusercontent.com/10311041/69565598-4573b500-0ff0-11ea-9b1f-9d6beb71d5e5.png)

**Comment by chengkaii** [comment]
![image](https://user-images.githubusercontent.com/10311041/69565629-558b9480-0ff0-11ea-9130-323628033333.png)

**Comment by wechat-miniprogram-admin** [comment]
已更新 readme，需要先 npm run init

**Comment by daipeihust** [comment]
> > src/weui-wxss 是一个 submodule 来的，必须要更新下来先。
> 
> 跑了也还是报错
> 
> ![image](https://user-images.githubusercontent.com/10311041/69565598-4573b500-0ff0-11ea-9b1f-9d6beb71d5e5.png)

要先在weui-miniprogram目录下运行npm install
