### ISSUE TITLE
表单自定义 validator 疑似 bug

### ISSUE THREAD

**Issue by zcfan** [wechat-miniprogram/weui-miniprogram#42]
我不确定是 bug 还是我的使用方法有问题，如果是用错了，希望能够补充一下正确的使用范例，目前文档中没有 validator 相关的 demo 。

form rules 配置如下：

```
[
      {
        name: "cardNo",
        rules: { validator: bankNoValidator }
      }
]
```

但 bankNoValidator 没有被调用，追溯到这里发现问题：

https://github.com/wechat-miniprogram/weui-miniprogram/blob/6c40363590d2a60f264fa22e128fc3d048b393bb/src/form/form-validator.ts#L8

ruleKey 为 validator 会被跳过，也就是说我必须再设置一个 message name 以外的字段才能让 validator 生效。按照文档，别的字段要么是内置校验规则，要么没有意义。如果是内置规则，下一条语句又会让内置规则失效，只执行 validator ，想不通这段逻辑的目的。

**Comment by cunjinli6** [comment]
v0.2版本已发布fixed
