### ISSUE TITLE
给uploader传入files数据后，再次上传报错

### ISSUE THREAD

**Issue by Grs24** [wechat-miniprogram/weui-miniprogram#49]
场景：用户修改资料页面，之前上传的图片数据传给uploader渲染后，再次上传的时候报错
`（err TypeError: Cannot set property 'url' of undefined）`

发现问题：在uploader源码里有段这样的代码：
```
if (json.urls) {
  var oldFiles = _this.data.files;
  json.urls.forEach(function (url, index) {
    oldFiles[len + index].url = url;
    oldFiles[len + index].loading = false;
  });
  _this.setData({
    files: oldFiles,
    currentFiles: newFiles
  });
  _this.triggerEvent('success', json, {});
}
```
json.urls应该就选择上传的图片路径数组，json.urls写了遍历，url应该是一个对象，而oldFiles[len + index].url的赋值应该是个图片路径字符串，这里赋值了url会发生报错

解决：
`oldFiles[len + index].url = url;` 改成：`oldFiles[len + index]= url;`

**Comment by cunjinli6** [comment]
传入的files应该是数组，每一项是Object，格式是{url, error, loading}

**Comment by Grs24** [comment]
对，没错，传入的files就是您说的对象数组，问题是

- 源码里的`json.urls.forEach(url,index){}` 此处的url就是一个对象吧？ 

- 然后`oldFiles[len + index].url = url; ` 此类的oldFiles同样也是

> `files应该是数组，每一项是Object，格式是{url, error, loading}`

 , `oldFiles[len + index].url = url` 不就报错了？ 应该改成`oldFiles[len + index]= url`
