### ISSUE TITLE
应当在文档中注明mp-tabbar图片路径以何为标准

### ISSUE THREAD

**Issue by DamonAmber** [wechat-miniprogram/weui-miniprogram#5]
应当在文档中标注，mp-tabbar的list中iconPath与selectedIconPath两项，不是以当前page的相对路径为准，而是以miniprogram_npm中的组件文件来计算相对路径。
当前文档中未明确注明，容易让新手以为是以当前page的js为相对路径的，导致mp-tabbar中图片一直无法正常显示

**Comment by cunjinli6** [comment]
文档已更新
