### ISSUE TITLE
录音接口更新

### ISSUE THREAD

**Issue by NineSu** [wechat-miniprogram/weui-miniprogram#53]
哥哥！案例中使用的录音API使用的是停止维护的API。能来个新API的案例吗。。。不同环境下不同回调事件会不执行。。。心好累。

**Comment by wechat-miniprogram-admin** [comment]
你说的是小程序示例么

**Comment by NineSu** [comment]
是的------------------ 原始邮件 ------------------
发件人: "Wechat Miniprogram"<notifications@github.com>
发送时间: 2020年2月14日(星期五) 晚上11:33
收件人: "wechat-miniprogram/weui-miniprogram"<weui-miniprogram@noreply.github.com>;
抄送: "NineSu"<1571071415@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wechat-miniprogram/weui-miniprogram] 录音接口更新 (#53)



你说的是小程序示例么
 
&mdash;

**Comment by seasonhuang** [comment]
请到小程序示例的 repo 提 issue。这个问题我们会更正下
