### ISSUE TITLE
使用按需下载组件形式，在app.wxss中引入样式失效

### ISSUE THREAD

**Issue by Fengmaybe** [wechat-miniprogram/weui-miniprogram#58]
1. 按需下载组件包
2. 在app.wxss中引入
@import './components/weui-miniprogram/weui-wxss/dist/style/weui.wxss';
3. 写组件时并没有出现正确的样式啊，好像引入的并没有生效。

**Comment by wechat-miniprogram-admin** [comment]
@import './components/weui-miniprogram/weui-wxss/dist/style/weui.wxss';
-----------
按需下载部分组件依赖 weui.wxss的样式，需通过npm单独引入。这个路径不对吧
