### ISSUE TITLE
npm run init出错

### ISSUE THREAD

**Issue by apple201700** [wechat-miniprogram/weui-miniprogram#6]
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Not found : @tencent/tslint-config-wxapp
npm ERR! 404
npm ERR! 404  '@tencent/tslint-config-wxapp' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404 It was specified as a dependency of 'weui-miniprogram'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by cunjinli6** [comment]
已修复
