### ISSUE TITLE
npm run init就出错了

### ISSUE THREAD

**Issue by chengkaii** [wechat-miniprogram/weui-miniprogram#62]
![image](https://user-images.githubusercontent.com/10311041/69598151-687b8480-1043-11ea-9618-d0647d2726c1.png)
这项目还有人管理么？

**Comment by LLLoneMa** [comment]
我也是  想看看怎么配置组件的，都不行@！！！

**Comment by chengkaii** [comment]
> 我也是 想看看怎么配置组件的，都不行@！！！
放弃了，不折腾了，其他的开源组件

**Comment by summer-wu** [comment]
看来是没人维护了

**Comment by xiangshenb** [comment]
报错 '../weui-wxss/src/style/widget/weui-tips/weui-actionsheet.wxss' wasn't found. Tried - D:\wxWork\weui-miniprogram\src\weui-wxss\src\style\widget\weui-tips\weui-actionsheet.wxss,D:\wxWork\weui-miniprogram\weui-wxss\src\style\widget\weui-tips\weui-actionsheet.wxss,..\weui-wxss\src\style\widget\weui-tips\weui-actionsheet.wxss in file D:\wxWork\weui-miniprogram\src\actionsheet\actionsheet.less line no. 2

**Comment by pqfom** [comment]
同样报错 官方大佬一直没人回复啊

**Comment by xysDavid** [comment]
已修复

**Comment by zhanlan123** [comment]
还是报错。还是对node.js的版本有要求。
