### ISSUE TITLE
build 失败？

### ISSUE THREAD

**Issue by weizuichunsun** [wechat-miniprogram/weui-miniprogram#79]
weui-miniprogram@0.2.2 dev: `gulp dev --develop`
npm ERR! Exit status 1

![image](https://user-images.githubusercontent.com/27394381/76373559-ac3c9480-637b-11ea-8450-c120cc83ad86.png)

**Comment by xysDavid** [comment]
看起来像是`weui-wxss`子模块没初始化，需要先运行下面的命令初始化项目：
```
npm run init
```

**Comment by weizuichunsun** [comment]
npm run init 也跑不起来

[0x7FF99775D3B0] ANOMALY: meaningless REX prefix used
PS F:\AppServ\www\github\weui-miniprogram-master> npm run init

> weui-miniprogram@0.2.2 init F:\AppServ\www\github\weui-miniprogram-master
> npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev


> weui-miniprogram@0.2.2 submodule F:\AppServ\www\github\weui-miniprogram-master
> git submodule init && git submodule update --init

C:/Program Files/Git/mingw64/libexec/git-core/git-sh-i18n: line 86: export: `[0x7FF99775D3B0]': not a valid identifier
C:/Program Files/Git/mingw64/libexec/git-core/git-sh-i18n: line 86: export: `ANOMALY:': not a valid identifier
fatal: not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! weui-miniprogram@0.2.2 submodule: `git submodule init && git submodule update --init`
npm ERR! Exit status 128
npm ERR!
npm ERR! Failed at the weui-miniprogram@0.2.2 submodule script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-03-12T06_31_35_044Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! weui-miniprogram@0.2.2 init: `npm run submodule && npm i && cd src/weui-wxss && npm i && gulp build:style && cd ../../ && npm run dev`
npm ERR! Exit status 128
npm ERR!
npm ERR! Failed at the weui-miniprogram@0.2.2 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-03-12T06_31_35_074Z-debug.log

**Comment by xysDavid** [comment]
@weizuichunsun 看起来像是你的`git`出了点问题导致的，可以查一下相关的报错信息如何解决。

**Comment by weizuichunsun** [comment]
如果卸载git 或者 未安装git 是否可行呢？

**Comment by xysDavid** [comment]
@weizuichunsun 恐怕不行，这里的`weui-wxss`是作为子模块引入的，依赖 git 进行初始化。
而且除非你日后都不用 git，否则你卸载了还是得装回来。

从错误日志来看，也有可能是你的 git 配置了代理，导致子模块更新不下来。

可以先看下有没有配置了代理

```bash
git config --global --get http.proxy
git config --global --get https.proxy
```

有的话把代理去掉

```bash
git config --global --unset http.proxy
git config --global --unset https.proxy
```

如果你的网络环境必须配置代理的话（比如某些公司或学校需要配置代理才可以正常上网），需要确认下代理是否可用；或者去掉代理后，切换到其他网络（比如手机热点）再重新试试。

**Comment by weizuichunsun** [comment]
没设置代理，仍不行，你确定你下载demo可以使用命令正常运行吗？

**Comment by xysDavid** [comment]
是的，也找有其他人试过没有问题。
或者你重新 clone 仓库下来试试？
```
git clone https://github.com/wechat-miniprogram/weui-miniprogram.git
```
然后再进入到仓库的根目录跑下面的命令初始化子模块
```
git submodule init && git submodule update --init
```
这样试试

**Comment by weizuichunsun** [comment]
![image](https://user-images.githubusercontent.com/27394381/76736584-0a191400-67a2-11ea-90d6-8358b42a2b14.png)

你好，执行的时候， git submodule init && git submodule update --init ，我的window 10 系统需要 改成     git submodule init ; git submodule update --init

然后根据重新 clone 命令，打包成功了，谢谢，

![image](https://user-images.githubusercontent.com/27394381/76736677-4187c080-67a2-11ea-97cf-d890835feb9a.png)
![image](https://user-images.githubusercontent.com/27394381/76736724-595f4480-67a2-11ea-99ec-aa081e45f99c.png)
