### ISSUE TITLE
Uploader 组件 source-type属性无效啊

### ISSUE THREAD

**Issue by pycainiao** [wechat-miniprogram/weui-miniprogram#80]
源代码里面，压根没有这个属性的使用。
实际的项目里，这个source-type也是一种显示为默认的状态
![image](https://user-images.githubusercontent.com/21077815/76388394-ffc2d880-63a3-11ea-8006-70ca60fc751f.png)

**Comment by xysDavid** [comment]
感谢反馈，我们修复一下

**Comment by lubezhang** [comment]
这个文件还是没有修复，请问有没有修复计划。

**Comment by lubezhang** [comment]
这个问题还是没有修复，请问有没有修复计划。

**Comment by sleafummer** [comment]
是的，同遇

**Comment by Jiny3213** [comment]
希望尽快修复
