### ISSUE TITLE
Loading组件bug

### ISSUE THREAD

**Issue by onekb** [wechat-miniprogram/weui-miniprogram#81]
使用版本
npm下载的0.2.2 和 网页“下载组件”的0.2.0都有该问题

表现情况
https://developers.weixin.qq.com/miniprogram/dev/extended/weui/loading.html
以下演示的该标签
```html
<mp-loading duration="{{900}}" ext-class="demo0" type="dot-gray" show="{{show}}" animated="{{animated}}"></mp-loading>
```
根据js控制，show每过2秒后会反转一下。
实测代码原本show=true，然后对其setData false是可以隐藏。但是对其setData true时，并不会重新显示。“小程序示例”小程序表现情况一样无法重新显示。

**Comment by xysDavid** [comment]
应该是动画处理导致的问题，可以暂时通过设置animated=false解决，后续版本会修复这个bug。

感谢反馈。
