### ISSUE TITLE
项目初始化运行npm init报错

### ISSUE THREAD

**Issue by zhanlan123** [wechat-miniprogram/weui-miniprogram#82]
![image](https://user-images.githubusercontent.com/7822852/77039497-04653d80-69f1-11ea-96be-78797704dcfc.png)

**Comment by xysDavid** [comment]
@zhanlan123 用的是哪个版本的 node.js ？

**Comment by xysDavid** [comment]
应该是 weui-wxss 中的 gulp 版本不支持在 node.js 12+ 环境下运行导致的，提了[相关 issue](https://github.com/Tencent/weui-wxss/issues/145) 跟进。

**Comment by zhanlan123** [comment]
难怪，我升级了node.js。看你们代码更新了。想运行一下就不行了。

**Comment by xysDavid** [comment]
@zhanlan123 可以尝试通过 [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md) 安装和切换不同版本的 node.js，临时解决一下这个问题。
