### ISSUE TITLE
使用weui.wxss后，tiptops和searchbar都无法正常使用

### ISSUE THREAD

**Issue by Xinchengzelin** [wechat-miniprogram/weui-miniprogram#84]
引入weui.wxss后，使用searchbar，开发者工具中点击搜索框没有反应？ 手机真机调试时左侧没有可点击的搜索图标，右侧没有取消？ toptips也是同样的无法弹出

https://developers.weixin.qq.com/community/develop/doc/000e8448d305e095301a43d3456400

**Comment by xysDavid** [comment]
@Xinchengzelin  想先了解下在 app.wxss 里面引入 weui.wxss 的原因是什么？是因为这个组件库里引用的 weui.wxss 的版本满足不了需求么？

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin 想先了解下在 app.wxss 里面引入 weui.wxss 的原因是什么？是因为这个组件库里引用的 weui.wxss 的版本满足不了需求么？

本来是想可以随时用weui中的样式，即便不在app.wxss中引入，在任意一个page引入，在这个page的tiptops和searchbar也没法用了。不知道有没有办法可以避免这种冲突？

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin 想先了解下在 app.wxss 里面引入 weui.wxss 的原因是什么？是因为这个组件库里引用的 weui.wxss 的版本满足不了需求么？
使用组件库外，还有一些组件是自己做的，也用到了weui.wxss，所以在 app.wxss 里引入了

**Comment by xysDavid** [comment]
@Xinchengzelin 有参考过[这里](https://developers.weixin.qq.com/miniprogram/dev/extended/weui/quickstart.html)的方式引入 weui.wxss 吗？ npm 包里面自带的 weui.wxss 的版本是配套使用的才不会有问题。

**Comment by Xinchengzelin** [comment]
@xysDavid 我是按教程那里引入的，将https://github.com/Tencent/weui-wxss的dist/style/weui.wxss文件拷贝到自己的项目lib下，然后按下图这样引入。是我的操作有什么问题吗？
![捕获](https://user-images.githubusercontent.com/30117686/77242726-8bf2bc80-6c3c-11ea-9eab-79a1fe2a2efe.PNG)

**Comment by xysDavid** [comment]
@Xinchengzelin 按需下载里面下载下来的组件，配套的不是最新版本的`weui.wxss`，从https://github.com/Tencent/weui-wxss 拷贝样式文件的话是最新版本的，两个版本就冲突了，所以会出现你遇到的问题。

如果不是必须使用最新版的`weui.wxss`的话，有两种方法：

1. 用 npm 包的方式引入，然后引用 npm 包中的 `weui.wxss` 文件
2. 把这个仓库 clone 到本地，执行`npm run init`后，再从`src/weui-wxss/dist`目录内，获取到对应版本的`weui.wxss`

然后再参考[demo](https://github.com/wechat-miniprogram/weui-miniprogram/tree/master/tools/demo)中的 wxml 结构去实现一个自己的组件。

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin 按需下载里面下载下来的组件，配套的不是最新版本的`weui.wxss`，从https://github.com/Tencent/weui-wxss 拷贝样式文件的话是最新版本的，两个版本就冲突了，所以会出现你遇到的问题。
> 
> 如果不是必须使用最新版的`weui.wxss`的话，有两种方法：
> 
> 1. 用 npm 包的方式引入，然后引用 npm 包中的 `weui.wxss` 文件
> 2. 把这个仓库 clone 到本地，执行`npm run init`后，再从`src/weui-wxss/dist`目录内，获取到对应版本的`weui.wxss`
> 
> 然后再参考[demo](https://github.com/wechat-miniprogram/weui-miniprogram/tree/master/tools/demo)中的 wxml 结构去实现一个自己的组件。

**Comment by Xinchengzelin** [comment]
@xysDavid 解决了我一个大问题，非常感谢你的指导，谢谢！

**Comment by xysDavid** [comment]
@Xinchengzelin 不客气
