### ISSUE TITLE
topTips的Bug

### ISSUE THREAD

**Issue by shmilyQin** [wechat-miniprogram/weui-miniprogram#87]
在没有导航栏,机型为iPhonex等有刘海屏的情况下,toptips显示不完
![55E94477-0437-43A8-95C5-6042B9567934](https://user-images.githubusercontent.com/20322678/78010621-28bc0500-7375-11ea-9686-8948cb63e8ab.png)

**Comment by xysDavid** [comment]
在自定义navigationBar的情况下会有这个问题，可以通过添加`ext-class`自定义toptips顶部的距离解决，组件内部不好兼容自定义navigationBar的情况。
