### ISSUE TITLE
npm 依赖安装失败

### ISSUE THREAD

**Issue by mrbeannnnn** [wechat-miniprogram/weui-miniprogram#9]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tencent%2ftslint-config-wxapp - Not found
npm ERR! 404
npm ERR! 404  '@tencent/tslint-config-wxapp@0.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'weui-miniprogram'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by cunjinli6** [comment]
已修复
