### ISSUE TITLE
请问什么时候更新 weui-wxss？

### ISSUE THREAD

**Issue by benlypan** [wechat-miniprogram/weui-miniprogram#92]
weui-wxss 已经更新到 2.3.0 版了，支持黑夜模式。weui-miniprogram 里引用的 weui-wxss 还是 2.0.1 版，请问什么时候可以更新一下？

**Comment by xysDavid** [comment]
已经有在更新适配了，近期会发布

**Comment by xysDavid** [comment]
1.0版本已更新，欢迎更新使用
