### ISSUE TITLE
mp-dialog弹窗组件不能垂直居中

### ISSUE THREAD

**Issue by teaxia** [wechat-miniprogram/weui-miniprogram#94]
新构建的项目，只引用了mp-dialog组件。
通过npm构建版本weui-miniprogram版本号1.0.2
弹窗组件不能垂直居中，真机测试也有该问题出现
![微信截图_20200426095841](https://user-images.githubusercontent.com/4031751/80295347-a4f30e00-87a4-11ea-9789-c2654bac975b.png)

**Comment by xysDavid** [comment]
v1.0.3 已修复
