### ISSUE TITLE
actionsheet等无展示

### ISSUE THREAD

**Issue by xiaoming20190803** [wechat-miniprogram/weui-miniprogram#95]
weui-miniprogram "version": "1.0.2" 
npm 构建后，微信小程序开发工具（1.02.1911180）打开miniprogram_dev，编译成功后，点actionsheet等组件，页面空白无展示。article有反应。

**Comment by xysDavid** [comment]
请问是直接从仓库中`npm run dev`后的`miniprogram_dev`打开的么？这边开发者工具`1.02.2003121`没有复现。
可以的话麻烦把`miniprogram_dev`目录单独创建一个[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)，把代码片段的链接提供一下。

**Comment by xiaoming20190803** [comment]
https://github.com/xiaoming20190803/miniprogram_dev

**Comment by xzsqhl** [comment]
解决了吗？我也碰到这个问题，npm run dev 会报错。。

**Comment by Tidyzq** [comment]
过期关闭
